### ISSUE TITLE
Ad-hoc mocks with same "interface" always use definition of first-mock.

### ISSUE THREAD

**Issue by jmalloc** [eloquent/phony#131]
```php
$foo = Phony::partialMock(['test' => function () { return 'foo'; }])->mock();
$bar = Phony::partialMock(['test' => function () { return 'bar'; }])->mock();

echo $foo->test() . PHP_EOL;
echo $bar->test() . PHP_EOL;
```

Expected output:
```
foo
bar
```

Actual output:
```
foo
foo
```

**Comment by ezzatron** [comment]
So there's a reason it's implemented the way it is. If Phony can determine that two mock definitions are "the same", it doesn't have to re-generate a new mock class each time. This is currently done via a combination of method name comparison + function signature comparison.

Simply using a `===` check will always fail because the custom methods are defined anew for each test, resulting in an explosion of generated mock classes.

I'll have to investigate, and see if it's feasible to inspect the closures for file & line information or some other nice way to get the best of both worlds here.
