### ISSUE TITLE
Explain the library name

### ISSUE THREAD

**Issue by mablae** [eloquent/phony#181]

**Comment by ezzatron** [comment]
Of course, no worries!

Mostly, it's just a word that starts with "Ph", similar to "PHP". It's a pretty common pattern for PHP projects to use a word that starts with "Ph", like [Phing], [Phinx], etc.

It's also common to take a word that starts with "F", and replace it with "Ph", because they have the same sound in English, like [Phake] \(pronounced the same as "Fake").

When I first created Phony, I was using [Phake] a lot, and it actually has a pretty similar name. The name "Phony" implies that the objects you are creating are impostors, or imitations of the original, which I think is pretty accurate.

"Phony" does have a negative connotation, but it's only in a light-hearted way.

[Phake]: https://github.com/mlively/Phake
[Phing]: https://github.com/phingofficial/phing
[Phinx]: https://github.com/robmorgan/phinx

**Comment by mablae** [comment]
Thank you!
