### ISSUE TITLE
Bug with generators

### ISSUE THREAD

**Issue by enumag** [eloquent/phony#191]
I've simplified my testcase to this:

```php
<?php

namespace Tests\Unit;

use Eloquent\Phony\Phpunit\Phony;

class Consumer
{
    public function consume()
    {
    }
}

class Provider
{
    public function create()
    {
        yield;
    }
}

class PhonyTest extends \PHPUnit_Framework_TestCase
{
    public function testPhony()
    {
        $consumer = Phony::mock(Consumer::class);
        $provider = Phony::mock(Provider::class);
        $provider->create->generates();
        $consumer->get()->consume($provider->get()->create());
        self::assertSame(
            $provider->create->firstCall()->returnValue(),
            $consumer->consume->firstCall()->argument(0)
        );
    }
}
```

The test above fails with unexpected error:

```
Failed asserting that two variables reference the same object.
```

I've tested that both arguments of the assert are indeed Generators. Just not the same generator which is a bug.

For confirmation I replaced the line `$provider->create->generates();` with `$provider->create->returns(new \DateTime);` - the test passes with that change.

**Comment by ezzatron** [comment]
I believe this is happening because of [generator spies](http://eloquent-software.com/phony/latest/#generator-and-iterable-verification).

In order to support generator verification, Phony has to wrap the original generator in another generator that records yielded values, received values and exceptions, return values, and thrown exceptions.

In this case, `$provider->create->firstCall()->returnValue()` is returning the un-wrapped generator, and `$consumer->consume->firstCall()->argument(0)` is returning the generator spy.

Generator spies are on by default, because in most cases code doesn't rely on a generator's identity (`===` comparison, `assertSame` etc.) You can disable them on a per-spy basis with [`setUseGeneratorSpies()`](http://eloquent-software.com/phony/0.13/#spy.setUseGeneratorSpies):

```php
class PhonyTest extends \PHPUnit_Framework_TestCase
{
    public function testPhony()
    {
        $consumer = Phony::mock(Consumer::class);
        $provider = Phony::mock(Provider::class);
        $provider->create->setUseGeneratorSpies(false);
        $provider->create->generates();
        $consumer->get()->consume($provider->get()->create());
        self::assertSame(
            $provider->create->firstCall()->returnValue(),
            $consumer->consume->firstCall()->argument(0)
        );
    }
}
```

I tried this with your test case and it passes once generator spies are disabled.

I think there might be room for improvement here, Phony might be able to automatically unwrap the generator spy when you call `argument()`, which would make cases like this "just work".

I'm not sure if any of this helps with your original use-case. Please let me know if this raises other issues, and thanks for taking the time to bring this up.

**Comment by enumag** [comment]
Thanks for the explanation! My original case is not much different so I'm sure this will help.

Unwrapping the generator when calling `argument`/`arguments` seems like a good idea. I'm curious about how this library works internally so maybe I will try sending a PR to solve it.

**Comment by enumag** [comment]
Is there anything other than generators that uses wrapping?

**Comment by ezzatron** [comment]
No worries!

Yes, there is similar "wrapping" for iterable values (see [Generator and iterable verification](http://eloquent-software.com/phony/0.13/#generator-and-iterable-verification)), which has to be enabled with [`setUseIterableSpies()`](http://eloquent-software.com/phony/0.13/#spy.setUseIterableSpies) because it changes the _type_ returned by the spy.

There's also a similar feature in Phony called [mock handle substitution](http://eloquent-software.com/phony/0.13/#mock-handle-substitution) where a mock handle can be used in place of the actual mock in lots of situations. In order to be consistent, this new "unwrapping" probably needs to function similarly. Once the concept is fleshed out, I can handle doing the bulk of that work, so don't worry too much about that.

Unwrapping iterable spies is definitely possible because I'm the one defining the iterable spy classes, so I can store the original iterable value and implement some way to retrieve it later when unwrapping.

Unwrapping generator spies is probably only going to be possible through some filthy hacks, because you cannot extend the `Generator` class to add anything to it. Even generator spies are just regular generators.

The only way I know of to add data to a generator is to use run-time properties (credit to @jmalloc for this method), like so:

```php
$f = function () {
    yield;
};
$g = $f();
$g->foo = "bar";

echo $g->foo;
```

Which [does seem to work across the board](https://3v4l.org/5mFQ6) at the moment, but strictly speaking there's no guarantee it will continue to work in future. It's a little bit gross, but it's all we have to work with.

**Comment by enumag** [comment]
Yeah that is a bit hacky. How about some map like `$map[spl_object_hash($wrapperValue)] = $realValue;`?

**Comment by ezzatron** [comment]
Actually, after some IRL discussion with @jmalloc, we came to the conclusion that it's probably better not to "unwrap" in `arguments()`, but rather to change Phony's _recording_ of return values so that when it wraps a value, the wrapped value itself is returned by `returnValue()`.

So instead of this order:
- Invoke function
- Record return value
- Wrap
- Return wrapped value to outside world

Change to this order:
- Invoke function
- Wrap
- Record wrapped return value
- Return wrapped value to outside world

I also think it's a better approach in general, because at the moment, Phony is kind of lying about what the return value really is.

I think this approach should still solve your use case (let me know if not), but in a way that doesn't wreak havoc in other areas of the API. It will also be a much simpler change, which is great.

I'll knock out a prototype in a branch ASAP.

**Comment by ezzatron** [comment]
@enumag Regarding the map, I don't think it's a good approach unfortunately.

Among other reasons, it requires a central store that may grow over time, and prevents garbage collection of every single generator and generator spy that Phony sees. Keeping the association in the spy avoids this (and some other issues).

In any case, I think I can get something working. Bear with me.

**Comment by enumag** [comment]
Your proposal will solve my use-case as well. But no need to rush, I'm fine with using setUseGeneratorSpies. Just take your time to do it right and let me know if I can help with anything.

**Comment by ezzatron** [comment]
Awesome! Will do.

**Comment by ezzatron** [comment]
@enumag Could you please confirm that the `wrapped-return-recording` branch works for your use case, even without `setUseGeneratorSpies(false)`?

You should be able to try it out by using `"eloquent/phony": "dev-wrapped-return-recording"` in your `composer.json`.

**Comment by enumag** [comment]
@ezzatron Confirmed. My test works with the new branch even after removing setUseGeneratorSpies.

**Comment by ezzatron** [comment]
@enumag Thanks! FYI I'm still prototyping some ideas here. Stay tuned :)

**Comment by enumag** [comment]
@ezzatron Sure, take your time. Thanks for your hard work! :-)

**Comment by ezzatron** [comment]
So here's what I'm currently thinking with regards to this issue; and I apologize, because I've changed my mind a few times now. But after trying a couple of implementations, I have a better grasp on what I think should happen.

I think it's best *not* to change the existing behavior of `returnValue()` or `argument()`. I realized that spies *already* faithfully record the input and output of the function being spied upon, and I was chasing a red herring there.

When a function returns a value, that *is* its return value, not what Phony wraps around it. When a function receives an argument, even if that argument happens to be a Phony wrapper, that *is* what it received as an argument. Obfuscating that just makes things more confusing in other circumstances.

So instead, what I *have* done, is to implement "iterable spy substitution" for generator and iterable spies. This will function in a very similar fashion to [mock handle substitution](http://eloquent-software.com/phony/0.13/#mock-handle-substitution). That is, it will allow Phony to use either an iterable spy, *or* the original value interchangeably in stubbing and verification, where appropriate.

This *may* help with your real use case, if we can figure out a way to get your verification happening via Phony instead of PHPUnit. But unfortunately I'm going to need more detail to know for sure.

I assume you're actually trying to test the thing that *uses* these providers and consumers. Am I on the right track? Can you show me an example of the actual code at all?

**Comment by enumag** [comment]
I'm not so sure about the `returnValue()`. In the case I described at the top you're correct. However if I'm remembering my experiments correctly this has the same (buggy) result: 

```
class PhonyTest extends \PHPUnit_Framework_TestCase
{
    public function testPhony()
    {
        $consumer = Phony::mock(Consumer::class);
        $provider = Phony::mock(Provider::class);
        $provider->create->returns(Phony::mock(\Generator::class)->get());
        $consumer->get()->consume($provider->get()->create());
        self::assertSame(
            $provider->create->firstCall()->returnValue(),
            $consumer->consume->firstCall()->argument(0)
        );
    }
}
```

In this case you can't say that the return value is the spy wrapper - it really is the mock itself. Also the code works fine if I change `\Generator::class` to `\DateTime::class`.

I can't share the code publicly but I can send it to you by e-mail if you want.

However you might want to consider simply not fixing it. The `setUseGeneratorSpies(false)` is fine once the programmer knows about it. If fixing this issue would mean too much code you don't like or could cause other problems elsewhere it really might be better to just add a note into documentation and leave it be. Personally I'm fine with that.

**Comment by ezzatron** [comment]
Yeah, I do have a bunch of extra documentation on the caveats of using iterable spies on a branch, so that should hopefully help. It's also great that `setUseGeneratorSpies(false)` solves your case.

To explain my point about `returnValue()`, let me try a simpler example:

```php
class PhonyTest extends \PHPUnit_Framework_TestCase
{
    public function testPhony()
    {
        $spy = Phony::spy('explode')->setUseIterableSpies(true);
        $spy('.', 'a.b');

        // both of these assertions pass
        $spy->returned(array('a', 'b'));
        $this->assertSame(array('a', 'b'), $spy->firstCall()->returnValue());
    }
}
```

I chose `explode()` simply because it returns an array, but you could sub in any similar function.

In this case, `explode()` is being spied on. The `explode()` function returned an array. Phony does wrap that value in an iterator spy afterward, but we're not trying to verify Phony's behavior, we're interested in what the system under test (in this case `explode()`) did.

P.S. I did try out the example you just posted, but it just fails because `Generator` is a final class, and I'm not sure I understand what it's demonstrating. Sorry.

**Comment by ezzatron** [comment]
@jmalloc Care to chime in?

**Comment by enumag** [comment]
I understand your point a little better now, thanks. :-)

I was trying to demonstrate a case where the current returnValue behavior made less sence than in your case. However I can't remember what the example looked like exactly.

There is probably no point in sending you my test not. I mean it is basically the same thing as in my original comment (as far as generators are concerned).

I'm fine with closing this issue (`setUseGeneratorSpies(false)` is a good enough solution imho). Close it if you feel the same way.

Thanks for your support!

**Comment by ezzatron** [comment]
Not a problem, thanks for taking the time to talk about it!

I'll make a new release and close the issue then. I'll also link back here with all the new documentation sections once they're up.

**Comment by ezzatron** [comment]
Relevant new sections in the documentation:

- [Iterable spy substitution](http://eloquent-software.com/phony/0.14/#iterable-spy-substitution)
- [Using iterable spies changes the return value](http://eloquent-software.com/phony/0.14/#using-iterable-spies-changes-the-return-value)
- [Nested iterable spies](http://eloquent-software.com/phony/0.14/#nested-iterable-spies)

There were also a bunch of [export format](http://eloquent-software.com/phony/0.14/#the-export-format) changes to help clarify what's going on in Phony's output. Including clearer exporting for wrapper types.
