### ISSUE TITLE
Feature detection breaks when errors are converted to exceptions

### ISSUE THREAD

**Issue by shadowhand** [eloquent/phony#209]
The Kohana framework converts [errors into exceptions](https://github.com/kohana/core/blob/bdbe81afb5a09cee4269d2e2210a0d293265231a/classes/Kohana/Core.php#L984-L995). This causes the feature detector to [throw an exception](https://github.com/eloquent/phony/blob/36bcb7ab99da22b2416eaf55b1ac9ccd73606782/src/Reflection/FeatureDetector.php#L546-L548) incorrectly.

```
ErrorException [ 4 ]: syntax error, unexpected '?', expecting variable (T_VARIABLE) ~ vendor/eloquent/phony/src/Reflection/FeatureDetector.php(532) : eval()'d code [ 1 ]
```

**Comment by ezzatron** [comment]
Thanks for the report!

There must be some other factor here, because Phony's test suite runs with a [similar error handler](https://github.com/php-errors/exceptions/blob/master/src/handler.php) in place, converting errors to exceptions. The same approach is also used at my workplace, and causes no issues.

There's probably still some deficiency in the feature detector that's causing this. I was working on a cleanup over in the [`feature-detector-review`](https://github.com/eloquent/phony/tree/feature-detector-review) branch. It has some changes that I think *may* fix this issue, to do with the types of exceptions that are caught and re-thrown inside the feature detector. If possible, would you be able to try this branch and see if you get better results?

Alternatively, could you help me out with some steps to reproduce this, so I can investigate? Is there an existing repo I can clone perhaps?

**Comment by shadowhand** [comment]
Same error with `feature-detector-review` branch. The error is happening because of `type.nullable` check. However, I managed to find the actual problem, which is that Kohana [catches errors on shutdown](https://github.com/kohana/core/blob/bdbe81afb5a09cee4269d2e2210a0d293265231a/classes/Kohana/Core.php#L1025-L1035) and then throws an exception. Turning off this functionality allows Phony to operate normally.

**Comment by ezzatron** [comment]
Glad you found a workaround.

I've been thinking about ways to mitigate this, but [`error_clear_last()`](http://php.net/error-clear-last) isn't available until PHP 7, and it seems that before that, there's no good way to clear the error returned by [`error_get_last()`](http://php.net/error-get-last). It might still be worthwhile to use [`error_clear_last()`](http://php.net/error-clear-last) when it *is* available.

**Comment by shadowhand** [comment]
We're nowhere near PHP 7 compatibility with Kohana right now. Good to know that function exists though.

**Comment by ezzatron** [comment]
This is just an idea, but perhaps the error handler could hang on to the last error it saw, and the fatal handler could only report on it if it hasn't already been handled by the error handler.

The logic being that if it's already passed through the error handler, then it's already been handled by the time the fatal handler sees it.
