### ISSUE TITLE
Another minor issue with matcher (?) output

### ISSUE THREAD

**Issue by jmalloc** [eloquent/phony#65]
It's frustrating when matcher expectations are truncated like so:

```
1) Icecave\Siphon\Score\BoxScore\BoxScoreReaderTest::testReadWithInnings
Expected call on {stub}[84] with arguments like:
    <'/sport/v2/baseball/MLB/boxsco...45.xml'>
Calls:
    - '/sport/v2/baseball/MLB/boxscores/2009/boxscore_MLB_12345.xml'
```

It would be great if matchers could use a diff the same way assertions do.  Perhaps single-line strings could use a word-diff.

I know this is part of a third-party library, it ties in with the other issue we talked about where you don't see array-diffs when an expectation fails on an array parameter. Obviously feel free to close if you don't intend to replace that.

**Comment by ezzatron** [comment]
As discussed, this becomes more complicated once there are multiple calls. Showing diff information would get very messy when that's the case. I think we should do #66, and just see how we feel about it then.

**Comment by jmalloc** [comment]
Yep.

But also... show diff if `count($calls) === 1` ??? :D :D +1

**Comment by ezzatron** [comment]
Thinking more on this, I don't think diff is the answer at all.

The only reasonable output I can think of is some kind of list of which argument matched, and which didn't, like so:

    1) Class::methodA
    Expected call on {stub}[111] with arguments like:
       <'argumentA'>, <is an integer>, <matches expression /^foo$/>
    Calls:
        Call 0:
            ✓ 'argumentA'
            ✗ 'argumentB'
            ✓ 'foo'
        Call 1:
            ✓ 'argumentA'
            ✓ 111
            ✓ 'foo'
            ✗ 'unexpected'
        Call 2:
            ✓ 'argumentA'
            ✓ 111
            ✗ <none>


which isn't even a diff at all.

Diff of the content of each argument would be prohibitively complicated, due to:
- How the fuck do you display a diff for each argument in the call, all at the same time?
- Since matcher implementations are sometimes provided by 3rd party libraries, how the fuck do you determine whether a diff even makes sense for the type of matcher, let alone what its 'value' is? I.e. how do you diff a regular expression matcher against the actual string?
- It could only be word diff anyway, multiline display would just look gross.

**Comment by ezzatron** [comment]
This of course assumes that no values get truncated, once we replace the exporter.

**Comment by ezzatron** [comment]
Closing because new exporter is working pretty well. Please open new issues as needed.
